config/routes.rb
Rails.application.routes.draw do
  # scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    namespace :danhmuc do
      match "/" => "base#index", :via => :get

      resources :nhombangcaps do
        get "delete"
      end
      resources :nhomkhoaphongs do
        get "delete"
      end
      resources :quoctiches do
        get "delete"
      end
      resources :vungdialies do
        get "delete"
      end
      resources :tinhthanhphos do
        get "delete"
      end
      resources :quanhuyens do
        get "delete"
      end
      resources :phuongxas do
        get "delete"
      end
      resources :dantocs do
        get "delete"
      end
      resources :tongiaos do
        get "delete"
      end
      resources :benhviens do
        get "delete"
      end
      resources :nganhangs do
        get "delete"
      end
      resources :bangcaps do
        get "delete"
      end
      resources :khoaphongs do
        get "delete"
      end
      resources :nhomchucdanhs do
        get "delete"
      end
      resources :chucdanhs do
        get "delete"
      end
      resources :nhomchucvus do
        get "delete"
      end
      resources :chucvus do
        get "delete"
      end
    end

    resources :nhanviens do
      get "delete"
    end

    root to: 'pages#home', :as => 'home'

    match '/about' => 'pages#about', :via => :get

    match '/laythongtinnhanvien' => 'pages#laythongtinnhanvien', :via => [:get, :post]
    match '/danh_sach_tinh_tp' => 'pages#danh_sach_tinh_tp', :via => [:get, :post],  :format => :json
    match '/danh_sach_quan_huyen' => 'pages#danh_sach_quan_huyen', :via => [:get, :post],  :format => :json
    match '/danh_sach_phuong_xa' => 'pages#danh_sach_phuong_xa', :via => [:get, :post],  :format => :json
    match '/quoctich' => 'pages#quoctich', :via => [:get],  :format => :json
    match '/dantoc' => 'pages#dantoc', :via => [:get],  :format => :json
    match '/tongiao' => 'pages#tongiao', :via => [:get],  :format => :json
    match '/gioitinh' => 'pages#gioitinh', :via => [:get],  :format => :json
    match '/tinhtranghonnhan' => 'pages#tinhtranghonnhan', :via => [:get],  :format => :json
    match '/nganhang' => 'pages#nganhang', :via => [:get],  :format => :json


  
  # match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  # match '', to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]
end

app/models/bangcap.rb
class Bangcap < ActiveRecord::Base
  belongs_to :nhombangcap

  validates :ma, :presence => true, :message => I18n.t('tinhthanhphos.delete.header')
  validates :ten, :presence => true
  validates :nhombangcap_id, :presence => true

  def self.search(search)
    if search
      where('ten LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/danhmuc/bangcaps_controller.rb
module Danhmuc
  class BangcapsController < BaseController

    respond_to :html, :js

    def index
      @bangcaps = Bangcap.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
    end

    def show
      @bangcap = Bangcap.find(params[:id])
    end

    def new
      @bangcap = Bangcap.new
    end

    def create
      @bangcaps = Bangcap.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @bangcap = Bangcap.create(bangcap_params)
    end

    def edit
      @bangcap = Bangcap.find(params[:id])
    end

    def update
      @bangcaps = Bangcap.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)

      @bangcap = Bangcap.find(params[:id])
      @bangcap.update_attributes(bangcap_params)
    end

    def destroy
      @bangcaps = Bangcap.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @bangcap = Bangcap.find(params[:id])
      @bangcap.destroy
    end

    def delete
      @bangcap = Bangcap.find(params[:bangcap_id])
    end

    private
    def bangcap_params
      params.require(:bangcap).permit(:ma, :ten, :nhombangcap_id)
    end
  end
end

app/controllers/danhmuc/base_controller.rb
module Danhmuc
  class BaseController < ApplicationController
    def index
      
    end
  end
end

app/controllers/danhmuc/benhviens_controller.rb
module Danhmuc
  class BenhviensController < BaseController

    respond_to :html, :js

    def index
      @benhviens = Benhvien.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
    end

    def show
      @benhvien = Benhvien.find(params[:id])
    end

    def new
      @benhvien = Benhvien.new
    end

    def create
      @benhviens = Benhvien.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @benhvien = Benhvien.create(benhvien_params)
    end

    def edit
      @benhvien = Benhvien.find(params[:id])
    end

    def update
      @benhviens = Benhvien.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)

      @benhvien = Benhvien.find(params[:id])
      @benhvien.update_attributes(benhvien_params)
    end

    def destroy
      @benhviens = Benhvien.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @benhvien = Benhvien.find(params[:id])
      @benhvien.destroy
    end

    def delete
      @benhvien = Benhvien.find(params[:benhvien_id])
    end

    private
    def benhvien_params
      params.require(:benhvien).permit(:ma, :ten, :diachi, :dienthoai)
    end
  end
end

app/controllers/danhmuc/chucdanhs_controller.rb
module Danhmuc
  class ChucdanhsController < BaseController

    respond_to :html, :js

    def index
      @chucdanhs = Chucdanh.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
    end

    # def show
    #   @chucdanh = Chucdanh.find(params[:id])
    # end

    def new
      @chucdanh = Chucdanh.new
    end

    def create
      @chucdanhs = Chucdanh.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @chucdanh = Chucdanh.create(chucdanh_params)
    end

    def edit
      @chucdanh = Chucdanh.find(params[:id])
    end

    def update
      @chucdanhs = Chucdanh.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)

      @chucdanh = Chucdanh.find(params[:id])
      @chucdanh.update_attributes(chucdanh_params)
    end

    def destroy
      @chucdanhs = Chucdanh.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @chucdanh = Chucdanh.find(params[:id])
      @chucdanh.destroy
    end

    def delete
      @chucdanh = Chucdanh.find(params[:chucdanh_id])
    end

    private
    def chucdanh_params
      params.require(:chucdanh).permit(:ma, :ten, :nhomchucdanh_id)
    end
  end
end

app/controllers/danhmuc/chucvus_controller.rb
module Danhmuc
  class ChucvusController < BaseController

    respond_to :html, :js

    def index
      @chucvus = Chucvu.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
    end

    # def show
    #   @chucvu = Chucvu.find(params[:id])
    # end

    def new
      @chucvu = Chucvu.new
    end

    def create
      @chucvus = Chucvu.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @chucvu = Chucvu.create(chucvu_params)
    end

    def edit
      @chucvu = Chucvu.find(params[:id])
    end

    def update
      @chucvus = Chucvu.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)

      @chucvu = Chucvu.find(params[:id])
      @chucvu.update_attributes(chucvu_params)
    end

    def destroy
      @chucvus = Chucvu.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @chucvu = Chucvu.find(params[:id])
      @chucvu.destroy
    end

    def delete
      @chucvu = Chucvu.find(params[:chucvu_id])
    end

    private
    def chucvu_params
      params.require(:chucvu).permit(:ma, :ten, :nhomchucvu_id)
    end
  end
end

app/controllers/danhmuc/dantocs_controller.rb
module Danhmuc
  class DantocsController < BaseController

    respond_to :html, :js

    def index
      @dantocs = Dantoc.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
    end

    def show
      @dantoc = Dantoc.find(params[:id])
    end

    def new
      @dantoc = Dantoc.new
    end

    def create
      @dantocs = Dantoc.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @dantoc = Dantoc.create(dantoc_params)
    end

    def edit
      @dantoc = Dantoc.find(params[:id])
    end

    def update
      @dantocs = Dantoc.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)

      @dantoc = Dantoc.find(params[:id])
      @dantoc.update_attributes(dantoc_params)
    end

    def destroy
      @dantocs = Dantoc.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @dantoc = Dantoc.find(params[:id])
      @dantoc.destroy
    end

    def delete
      @dantoc = Dantoc.find(params[:dantoc_id])
    end

    private
    def dantoc_params
      params.require(:dantoc).permit(:ma, :ten)
    end

  end
end

app/controllers/danhmuc/khoaphongs_controller.rb
module Danhmuc
  class KhoaphongsController < BaseController

    respond_to :html, :js

    def index
      @khoaphongs = Khoaphong.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
    end

    def show
      @khoaphong = Khoaphong.find(params[:id])
    end

    def new
      @khoaphong = Khoaphong.new
    end

    def create
      @khoaphongs = Khoaphong.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @khoaphong = Khoaphong.create(khoaphong_params)
    end

    def edit
      @khoaphong = Khoaphong.find(params[:id])
    end

    def update
      @khoaphongs = Khoaphong.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)

      @khoaphong = Khoaphong.find(params[:id])
      @khoaphong.update_attributes(khoaphong_params)
    end

    def destroy
      @khoaphongs = Khoaphong.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @khoaphong = Khoaphong.find(params[:id])
      @khoaphong.destroy
    end

    def delete
      @khoaphong = Khoaphong.find(params[:khoaphong_id])
    end

    private
    def khoaphong_params
      params.require(:khoaphong).permit(:ma, :ten, :nhomkhoaphong_id)
    end
  end
end

app/controllers/danhmuc/nganhangs_controller.rb
module Danhmuc
  class NganhangsController < BaseController

    respond_to :html, :js

    def index
      @nganhangs = Nganhang.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
    end

    def show
      @nganhang = Nganhang.find(params[:id])
    end

    def new
      @nganhang = Nganhang.new
    end

    def create
      @nganhangs = Nganhang.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @nganhang = Nganhang.create(nganhang_params)
    end

    def edit
      @nganhang = Nganhang.find(params[:id])
    end

    def update
      @nganhangs = Nganhang.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)

      @nganhang = Nganhang.find(params[:id])
      @nganhang.update_attributes(nganhang_params)
    end

    def destroy
      @nganhangs = Nganhang.search(params[:search]).order(:ten).paginate(:page => params[:page], :per_page => 12)
      @nganhang = Nganhang.find(params[:id])
      @nganhang.destroy
    end

    def delete
      @nganhang = Nganhang.find(params[:nganhang_id])
    end

    private
    def nganhang_params
      params.require(:nganhang).permit(:ma, :ten, :thongtin)
    end
  end
end

app/controllers/danhmuc/nhombangcaps_controller.rb
module Danhmuc
  class NhombangcapsController < BaseController

    respond_to :html, :js

    def index
      @nhombangcaps = Nhombangcap.all
    end

    def show
      @nhombangcap = Nhombangcap.find(params[:id])
    end

    def new
      @nhombangcap = Nhombangcap.new
    end

    def create
      @nhombangcaps = Nhombangcap.all
      @nhombangcap = Nhombangcap.create(nhombangcap_params)
    end

    def edit
      @nhombangcap = Nhombangcap.find(params[:id])
    end

    def update
      @nhombangcaps = Nhombangcap.all
      @nhombangcap = Nhombangcap.find(params[:id])

      @nhombangcap.update_attributes(nhombangcap_params)
    end

    def delete
      @nhombangcap = Nhombangcap.find(params[:nhombangcap_id])
    end

    def destroy
      @nhombangcaps = Nhombangcap.all
      @nhombangcap = Nhombangcap.find(params[:id])
      @nhombangcap.destroy
    end

    private
    def nhombangcap_params
      params.require(:nhombangcap).permit(:ma, :ten, :diengiai)
    end
  end
end

app/controllers/danhmuc/nhomchucdanhs_controller.rb
module Danhmuc
  class NhomchucdanhsController < BaseController

    respond_to :html, :js

    def index
      @nhomchucdanhs = Nhomchucdanh.all
    end

    def show
      @nhomchucdanh = Nhomchucdanh.find(params[:id])
    end

    def new
      @nhomchucdanh = Nhomchucdanh.new
    end

    def create
      @nhomchucdanhs = Nhomchucdanh.all
      @nhomchucdanh = Nhomchucdanh.create(nhomchucdanh_params)
    end

    def edit
      @nhomchucdanh = Nhomchucdanh.find(params[:id])
    end

    def update
      @nhomchucdanhs = Nhomchucdanh.all
      @nhomchucdanh = Nhomchucdanh.find(params[:id])

      @nhomchucdanh.update_attributes(nhomchucdanh_params)
    end

    def delete
      @nhomchucdanh = Nhomchucdanh.find(params[:nhomchucdanh_id])
    end

    def destroy
      @nhomchucdanhs = Nhomchucdanh.all
      @nhomchucdanh = Nhomchucdanh.find(params[:id])
      @nhomchucdanh.destroy
    end

    private
    def nhomchucdanh_params
      params.require(:nhomchucdanh).permit(:ma, :ten, :diengiai)
    end
  end
end

app/controllers/danhmuc/nhomchucvus_controller.rb
module Danhmuc
  class NhomchucvusController < BaseController

    respond_to :html, :js

    def index
      @nhomchucvus = Nhomchucvu.all
    end

    def show
      @nhomchucvu = Nhomchucvu.find(params[:id])
    end

    def new
      @nhomchucvu = Nhomchucvu.new
    end

    def create
      @nhomchucvus = Nhomchucvu.all
      @nhomchucvu = Nhomchucvu.create(nhomchucvu_params)
    end

    def edit
      @nhomchucvu = Nhomchucvu.find(params[:id])
    end

    def update
      @nhomchucvus = Nhomchucvu.all
      @nhomchucvu = Nhomchucvu.find(params[:id])

      @nhomchucvu.update_attributes(nhomchucvu_params)
    end

    def delete
      @nhomchucvu = Nhomchucvu.find(params[:nhomchucvu_id])
    end

    def destroy
      @nhomchucvus = Nhomchucvu.all
      @nhomchucvu = Nhomchucvu.find(params[:id])
      @nhomchucvu.destroy
    end

    private
    def nhomchucvu_params
      params.require(:nhomchucvu).permit(:ma, :ten, :diengiai)
    end
  end
end

app/controllers/danhmuc/nhomkhoaphongs_controller.rb
module Danhmuc
  class NhomkhoaphongsController < BaseController

    respond_to :html, :js

    def index
      @nhomkhoaphongs = Nhomkhoaphong.all
    end

    def show
      @nhomkhoaphong = Nhomkhoaphong.find(params[:id])
    end

    def new
      @nhomkhoaphong = Nhomkhoaphong.new
    end

    def create
      @nhomkhoaphongs = Nhomkhoaphong.all
      @nhomkhoaphong = Nhomkhoaphong.create(nhomkhoaphong_params)
    end

    def edit
      @nhomkhoaphong = Nhomkhoaphong.find(params[:id])
    end

    def update
      @nhomkhoaphongs = Nhomkhoaphong.all

      @nhomkhoaphong = Nhomkhoaphong.find(params[:id])
      @nhomkhoaphong.update_attributes(nhomkhoaphong_params)
    end

    def destroy
      @nhomkhoaphongs = Nhomkhoaphong.all
      @nhomkhoaphong = Nhomkhoaphong.find(params[:id])
      @nhomkhoaphong.destroy
    end

    def delete
      @nhomkhoaphong = Nhomkhoaphong.find(params[:nhomkhoaphong_id])
    end

    private
    def nhomkhoaphong_params
      params.require(:nhomkhoaphong).permit(:ma, :ten)
    end

  end
end

app/controllers/danhmuc/phuongxas_controller.rb
module Danhmuc
  class PhuongxasController < BaseController

    helper_method :sort_column, :sort_direction
    respond_to :html, :js

    def index
      @phuongxas = Phuongxa.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 12)
    end

    def show
      @phuongxa = Phuongxa.find(params[:id])
    end

    def edit
      @phuongxa = Phuongxa.find(params[:id])
    end

    def update
      @phuongxas = Phuongxa.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 12)
      @phuongxa = Phuongxa.find(params[:id])
      @phuongxa.update_attributes(phuongxa_params)
    end

    def new
      @phuongxa = Phuongxa.new
    end

    def create
      @phuongxas = Phuongxa.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 12)
      @phuongxa = Phuongxa.create(phuongxa_params)
    end

    def delete
      @phuongxa = Phuongxa.find(params[:phuongxa_id])
    end

    def destroy
      @phuongxas = Phuongxa.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 12)
      @phuongxa = Phuongxa.find(params[:id])
      @phuongxa.destroy
    end

    private
    def phuongxa_params
      params.require(:phuongxa).permit(:ma, :ten, :quanhuyen_id)
    end

    def sort_column
      Phuongxa.column_names.include?(params[:sort]) ? params[:sort] : "ten"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

  end
end

app/helpers/bangcaps_helper.rb
module BangcapsHelper
end

app/views/danhmuc/bangcaps/_delete.html.erb
<div class="modal-header">
  <h3><%= t "bangcaps.delete.header" %></h3>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  <%= t "bangcaps.question" %><b><%= @bangcap.ten %></b>?
</div>
<div class="modal-footer">
  <%= link_to danhmuc_bangcap_path(@bangcap), method: :delete, :data => {remote: true}, class: "btn btn-danger" do %>
      <i class="glyphicon glyphicon-ok-sign"></i> <%= t "yes" %>
  <% end %>
  <%= link_to danhmuc_bangcaps_path, class: "btn btn-default", data: {dismiss: "modal"} do %>
      <i class="glyphicon glyphicon-remove-sign"></i> <%= t "no" %>
  <% end %>
</div>

app/views/danhmuc/bangcaps/_edit.html.erb
<div class="modal-header">
  <h3><%= t "bangcaps.edit.header" %><b><%= @bangcap.ten %></b></h3>
</div>
<%= render "form" %>

app/views/danhmuc/bangcaps/_form.html.erb
<%= form_for ([:danhmuc, @bangcap]), :data => {remote: true}, :html => {:class => "form-horizontal", role: "form"} do |f| %>
    <div class="modal-body">
      <div class="row">
        <ul class="errors"></ul>
      </div>
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
          <div class="form-group">
            <label for="ma"><%= t "bangcaps.ma" %></label>
            <%= f.text_field :ma, class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="ten"><%= t "bangcaps.ten" %></label>
            <%= f.text_field :ten, class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="nhombangcap_id"><%= t "bangcaps.nhombangcap_id" %></label>
            <%= f.select(:nhombangcap_id, Nhombangcap.all.collect { |c| [c.ten, c.id] }, {:prompt => t('bangcaps.promt')}, {class: "form-control"}) %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">
          <i class="glyphicon glyphicon-floppy-save"></i> <%= t "save" %>
        </button>
        <%= link_to danhmuc_bangcaps_path, class: "btn btn-default", data: {dismiss: "modal"} do %>
            <i class="glyphicon glyphicon-chevron-left"></i> <%= t "back" %>
        <% end %>
      </div>
      <div class="col-lg-3"></div>
    </div>
<% end %>

app/views/danhmuc/bangcaps/_index.html.erb
<table class="table table-hover ta">
  <thead>
  <tr>
    <th style="width: 150px;"><%= t "bangcaps.ma" %></th>
    <th><%= t "bangcaps.ten" %></th>
    <th><%= t "bangcaps.nhombangcap_id" %></th>
    <td style="width: 60px;">&nbsp;</td>
  </tr>
  </thead>
  <tbody>
  <% @bangcaps.each do |bangcap| %>
      <tr>
        <td><%= bangcap.ma %></td>
        <td><%= bangcap.ten %></td>
        <td><%= bangcap.nhombangcap.ten %></td>
        <td><%= link_to edit_danhmuc_bangcap_path(bangcap), data: {remote: true}, :title => t('edit') do %>
              <i class="glyphicon glyphicon-edit"></i>
          <% end %>
          <%= link_to danhmuc_bangcap_delete_path(bangcap), data: {remote: true}, :title => t('delete') do %>
              <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr class="text-center">
    <td colspan="3">
      <%= will_paginate @bangcaps, renderer: BootstrapPagination::Rails %>
    </td>
  </tr>
  </tfoot>
</table>

app/views/danhmuc/bangcaps/_new.html.erb
<div class="modal-header">
  <h3><%= t "bangcaps.new.header" %></h3>
</div>
<%= render "form" %>

app/views/danhmuc/bangcaps/_save.js.erb
$("ul.errors").html("")
<% if @bangcap.errors.any? %>
<% @bangcap.errors.full_messages.each do |message| %>
$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
<% end %>
<% else %>
$(".form-index").html("<%= escape_javascript(render 'index') %>")
$("#form-modal").modal("hide")
<% end %>

app/views/danhmuc/bangcaps/create.js.erb
<%= render "save" %>

app/views/danhmuc/bangcaps/delete.js.erb
$("#inner-form-modal").html("<%= escape_javascript(render 'delete') %>")
$("#form-modal").modal("show")

app/views/danhmuc/bangcaps/destroy.js.erb
<%= render "save" %>

app/views/danhmuc/bangcaps/edit.js.erb
$("#inner-form-modal").html("<%= escape_javascript(render 'danhmuc/bangcaps/edit') %>")
$("#form-modal").modal("show")

app/views/danhmuc/bangcaps/index.html.erb
<div class="page-header">
  <h1 class="pull-left"><%= t "bangcaps.index.header" %></h1>
  <%= link_to new_danhmuc_bangcap_path, remote: true, class: "btn btn-primary pull-right" do %>
      <i class="glyphicon glyphicon-plus-sign"></i> <%= t('new') %>
  <% end %>
  <div class="clearfix"></div>
</div>
<div class="new-form"></div>
<%= form_tag danhmuc_bangcaps_path, :method => 'get', :id => "ajax_search" do %>
    <div class="row">
      <div class="col-lg-6">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
          <%= text_field_tag :search, params[:search], :placeholder => t('bangcaps.keysearch'), :class => "form-control" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="form-index">
        <%= render "index" %>
      </div>
    </div>
<% end %>
<div id="form-modal" class="modal fade">
  <div class="modal-dialog">
    <div id="inner-form-modal" class="modal-content"></div>
  </div>
</div>

app/views/danhmuc/bangcaps/index.js.erb
$(".form-index").html("<%= escape_javascript(render("index")) %>");

app/views/danhmuc/bangcaps/new.js.erb
$("#inner-form-modal").html("<%= escape_javascript(render 'new') %>")
$("#form-modal").modal("show")

app/views/danhmuc/bangcaps/update.js.erb
<%= render "save" %>